# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adib/Documents/Project/SFML_GAME

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adib/Documents/Project/SFML_GAME

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adib/Documents/Project/SFML_GAME/CMakeFiles /home/adib/Documents/Project/SFML_GAME//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adib/Documents/Project/SFML_GAME/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Game

# Build rule for target.
Game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Game
.PHONY : Game

# fast build rule for target.
Game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/build
.PHONY : Game/fast

Scene/Main/InputHandler/MainCommands.o: Scene/Main/InputHandler/MainCommands.cpp.o
.PHONY : Scene/Main/InputHandler/MainCommands.o

# target to build an object file
Scene/Main/InputHandler/MainCommands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Scene/Main/InputHandler/MainCommands.cpp.o
.PHONY : Scene/Main/InputHandler/MainCommands.cpp.o

Scene/Main/InputHandler/MainCommands.i: Scene/Main/InputHandler/MainCommands.cpp.i
.PHONY : Scene/Main/InputHandler/MainCommands.i

# target to preprocess a source file
Scene/Main/InputHandler/MainCommands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Scene/Main/InputHandler/MainCommands.cpp.i
.PHONY : Scene/Main/InputHandler/MainCommands.cpp.i

Scene/Main/InputHandler/MainCommands.s: Scene/Main/InputHandler/MainCommands.cpp.s
.PHONY : Scene/Main/InputHandler/MainCommands.s

# target to generate assembly for a file
Scene/Main/InputHandler/MainCommands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Scene/Main/InputHandler/MainCommands.cpp.s
.PHONY : Scene/Main/InputHandler/MainCommands.cpp.s

Scene/Main/InputHandler/MainInputHandler.o: Scene/Main/InputHandler/MainInputHandler.cpp.o
.PHONY : Scene/Main/InputHandler/MainInputHandler.o

# target to build an object file
Scene/Main/InputHandler/MainInputHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Scene/Main/InputHandler/MainInputHandler.cpp.o
.PHONY : Scene/Main/InputHandler/MainInputHandler.cpp.o

Scene/Main/InputHandler/MainInputHandler.i: Scene/Main/InputHandler/MainInputHandler.cpp.i
.PHONY : Scene/Main/InputHandler/MainInputHandler.i

# target to preprocess a source file
Scene/Main/InputHandler/MainInputHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Scene/Main/InputHandler/MainInputHandler.cpp.i
.PHONY : Scene/Main/InputHandler/MainInputHandler.cpp.i

Scene/Main/InputHandler/MainInputHandler.s: Scene/Main/InputHandler/MainInputHandler.cpp.s
.PHONY : Scene/Main/InputHandler/MainInputHandler.s

# target to generate assembly for a file
Scene/Main/InputHandler/MainInputHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Scene/Main/InputHandler/MainInputHandler.cpp.s
.PHONY : Scene/Main/InputHandler/MainInputHandler.cpp.s

Scene/Main/MainScene.o: Scene/Main/MainScene.cpp.o
.PHONY : Scene/Main/MainScene.o

# target to build an object file
Scene/Main/MainScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Scene/Main/MainScene.cpp.o
.PHONY : Scene/Main/MainScene.cpp.o

Scene/Main/MainScene.i: Scene/Main/MainScene.cpp.i
.PHONY : Scene/Main/MainScene.i

# target to preprocess a source file
Scene/Main/MainScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Scene/Main/MainScene.cpp.i
.PHONY : Scene/Main/MainScene.cpp.i

Scene/Main/MainScene.s: Scene/Main/MainScene.cpp.s
.PHONY : Scene/Main/MainScene.s

# target to generate assembly for a file
Scene/Main/MainScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Scene/Main/MainScene.cpp.s
.PHONY : Scene/Main/MainScene.cpp.s

component/GameManager.o: component/GameManager.cpp.o
.PHONY : component/GameManager.o

# target to build an object file
component/GameManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/component/GameManager.cpp.o
.PHONY : component/GameManager.cpp.o

component/GameManager.i: component/GameManager.cpp.i
.PHONY : component/GameManager.i

# target to preprocess a source file
component/GameManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/component/GameManager.cpp.i
.PHONY : component/GameManager.cpp.i

component/GameManager.s: component/GameManager.cpp.s
.PHONY : component/GameManager.s

# target to generate assembly for a file
component/GameManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/component/GameManager.cpp.s
.PHONY : component/GameManager.cpp.s

component/Scene.o: component/Scene.cpp.o
.PHONY : component/Scene.o

# target to build an object file
component/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/component/Scene.cpp.o
.PHONY : component/Scene.cpp.o

component/Scene.i: component/Scene.cpp.i
.PHONY : component/Scene.i

# target to preprocess a source file
component/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/component/Scene.cpp.i
.PHONY : component/Scene.cpp.i

component/Scene.s: component/Scene.cpp.s
.PHONY : component/Scene.s

# target to generate assembly for a file
component/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/component/Scene.cpp.s
.PHONY : component/Scene.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Game"
	@echo "... Scene/Main/InputHandler/MainCommands.o"
	@echo "... Scene/Main/InputHandler/MainCommands.i"
	@echo "... Scene/Main/InputHandler/MainCommands.s"
	@echo "... Scene/Main/InputHandler/MainInputHandler.o"
	@echo "... Scene/Main/InputHandler/MainInputHandler.i"
	@echo "... Scene/Main/InputHandler/MainInputHandler.s"
	@echo "... Scene/Main/MainScene.o"
	@echo "... Scene/Main/MainScene.i"
	@echo "... Scene/Main/MainScene.s"
	@echo "... component/GameManager.o"
	@echo "... component/GameManager.i"
	@echo "... component/GameManager.s"
	@echo "... component/Scene.o"
	@echo "... component/Scene.i"
	@echo "... component/Scene.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

